export const countries = [
    { "es": "Estados Unidos", "en": "United States", "code": "US" },
    { "es": "México", "en": "Mexico", "code": "MX" },
    { "es": "España", "en": "Spain", "code": "ES" },
    { "es": "Afganistán", "en": "Afghanistan", "code": "AF" },
    { "es": "Islas Aland", "en": "Aland Islands", "code": "AX" },
    { "es": "Albania", "en": "Albania", "code": "AL" },
    { "es": "Argelia", "en": "Algeria", "code": "DZ" },
    { "es": "Samoa Americana", "en": "American Samoa", "code": "AS" },
    { "es": "Andorra", "en": "Andorra", "code": "AD" },
    { "es": "Angola", "en": "Angola", "code": "AO" },
    { "es": "Anguila", "en": "Anguilla", "code": "AI" },
    { "es": "Antártida", "en": "Antarctica", "code": "AQ" },
    { "es": "Antigua y Barbuda", "en": "Antigua and Barbuda", "code": "AG" },
    { "es": "Argentina", "en": "Argentina", "code": "AR" },
    { "es": "Armenia", "en": "Armenia", "code": "AM" },
    { "es": "Aruba", "en": "Aruba", "code": "AW" },
    { "es": "Australia", "en": "Australia", "code": "AU" },
    { "es": "Austria", "en": "Austria", "code": "AT" },
    { "es": "Azerbaiyán", "en": "Azerbaijan", "code": "AZ" },
    { "es": "Bahamas", "en": "Bahamas", "code": "BS" },
    { "es": "Baréin", "en": "Bahrain", "code": "BH" },
    { "es": "Bangladés", "en": "Bangladesh", "code": "BD" },
    { "es": "Barbados", "en": "Barbados", "code": "BB" },
    { "es": "Bielorrusia", "en": "Belarus", "code": "BY" },
    { "es": "Bélgica", "en": "Belgium", "code": "BE" },
    { "es": "Belice", "en": "Belize", "code": "BZ" },
    { "es": "Benín", "en": "Benin", "code": "BJ" },
    { "es": "Bermudas", "en": "Bermuda", "code": "BM" },
    { "es": "Bután", "en": "Bhutan", "code": "BT" },
    { "es": "Bolivia", "en": "Bolivia", "code": "BO" },
    { "es": "Bonaire", "en": "Bonaire, Sint Eustatius and Saba", "code": "BQ" },
    { "es": "Bosnia y Herzegovina", "en": "Bosnia and Herzegovina", "code": "BA" },
    { "es": "Botsuana", "en": "Botswana", "code": "BW" },
    { "es": "Isla Bouvet", "en": "Bouvet Island", "code": "BV" },
    { "es": "Brasil", "en": "Brazil", "code": "BR" },
    { "es": "Territorio Británico del Océano Índico", "en": "British Indian Ocean Territory", "code": "IO" },
    { "es": "Brunéi", "en": "Brunei Darussalam", "code": "BN" },
    { "es": "Bulgaria", "en": "Bulgaria", "code": "BG" },
    { "es": "Burkina Faso", "en": "Burkina Faso", "code": "BF" },
    { "es": "Burundi", "en": "Burundi", "code": "BI" },
    { "es": "Camboya", "en": "Cambodia", "code": "KH" },
    { "es": "Camerún", "en": "Cameroon", "code": "CM" },
    { "es": "Canadá", "en": "Canada", "code": "CA" },
    { "es": "Cabo Verde", "en": "Cape Verde", "code": "CV" },
    { "es": "Islas Caimán", "en": "Cayman Islands", "code": "KY" },
    { "es": "República Centroafricana", "en": "Central African Republic", "code": "CF" },
    { "es": "Chad", "en": "Chad", "code": "TD" },
    { "es": "Chile", "en": "Chile", "code": "CL" },
    { "es": "China", "en": "China", "code": "CN" },
    { "es": "Isla de Navidad", "en": "Christmas Island", "code": "CX" },
    { "es": "Islas Cocos", "en": "Cocos (Keeling) Islands", "code": "CC" },
    { "es": "Colombia", "en": "Colombia", "code": "CO" },
    { "es": "Comoras", "en": "Comoros", "code": "KM" },
    { "es": "Congo", "en": "Congo", "code": "CG" },
    { "es": "República Democrática del Congo", "en": "Democratic Republic of the Congo", "code": "CD" },
    { "es": "Islas Cook", "en": "Cook Islands", "code": "CK" },
    { "es": "Costa Rica", "en": "Costa Rica", "code": "CR" },
    { "es": "Costa de Marfil", "en": "Cote D'Ivoire", "code": "CI" },
    { "es": "Croacia", "en": "Croatia", "code": "HR" },
    { "es": "Cuba", "en": "Cuba", "code": "CU" },
    { "es": "Curazao", "en": "Curacao", "code": "CW" },
    { "es": "Chipre", "en": "Cyprus", "code": "CY" },
    { "es": "República Checa", "en": "Czech Republic", "code": "CZ" },
    { "es": "Dinamarca", "en": "Denmark", "code": "DK" },
    { "es": "Yibuti", "en": "Djibouti", "code": "DJ" },
    { "es": "Dominica", "en": "Dominica", "code": "DM" },
    { "es": "República Dominicana", "en": "Dominican Republic", "code": "DO" },
    { "es": "Ecuador", "en": "Ecuador", "code": "EC" },
    { "es": "Egipto", "en": "Egypt", "code": "EG" },
    { "es": "El Salvador", "en": "El Salvador", "code": "SV" },
    { "es": "Guinea Ecuatorial", "en": "Equatorial Guinea", "code": "GQ" },
    { "es": "Eritrea", "en": "Eritrea", "code": "ER" },
    { "es": "Estonia", "en": "Estonia", "code": "EE" },
    { "es": "Etiopía", "en": "Ethiopia", "code": "ET" },
    { "es": "Islas Malvinas", "en": "Falkland Islands (Malvinas)", "code": "FK" },
    { "es": "Islas Feroe", "en": "Faroe Islands", "code": "FO" },
    { "es": "Fiyi", "en": "Fiji", "code": "FJ" },
    { "es": "Finlandia", "en": "Finland", "code": "FI" },
    { "es": "Francia", "en": "France", "code": "FR" },
    { "es": "Guayana Francesa", "en": "French Guiana", "code": "GF" },
    { "es": "Polinesia Francesa", "en": "French Polynesia", "code": "PF" },
    { "es": "Gabón", "en": "Gabon", "code": "GA" },
    { "es": "Gambia", "en": "Gambia", "code": "GM" },
    { "es": "Georgia", "en": "Georgia", "code": "GE" },
    { "es": "Alemania", "en": "Germany", "code": "DE" },
    { "es": "Ghana", "en": "Ghana", "code": "GH" },
    { "es": "Gibraltar", "en": "Gibraltar", "code": "GI" },
    { "es": "Grecia", "en": "Greece", "code": "GR" },
    { "es": "Groenlandia", "en": "Greenland", "code": "GL" },
    { "es": "Granada", "en": "Grenada", "code": "GD" },
    { "es": "Guadalupe", "en": "Guadeloupe", "code": "GP" },
    { "es": "Guam", "en": "Guam", "code": "GU" },
    { "es": "Guatemala", "en": "Guatemala", "code": "GT" },
    { "es": "Guernsey", "en": "Guernsey", "code": "GG" },
    { "es": "Guinea", "en": "Guinea", "code": "GN" },
    { "es": "Guinea-Bisáu", "en": "Guinea-Bissau", "code": "GW" },
    { "es": "Guyana", "en": "Guyana", "code": "GY" },
    { "es": "Haití", "en": "Haiti", "code": "HT" },
    { "es": "Honduras", "en": "Honduras", "code": "HN" },
    { "es": "Hong Kong", "en": "Hong Kong", "code": "HK" },
    { "es": "Hungría", "en": "Hungary", "code": "HU" },
    { "es": "Islandia", "en": "Iceland", "code": "IS" },
    { "es": "India", "en": "India", "code": "IN" },
    { "es": "Indonesia", "en": "Indonesia", "code": "ID" },
    { "es": "Irán", "en": "Iran", "code": "IR" },
    { "es": "Irak", "en": "Iraq", "code": "IQ" },
    { "es": "Irlanda", "en": "Ireland", "code": "IE" },
    { "es": "Isla de Man", "en": "Isle of Man", "code": "IM" },
    { "es": "Israel", "en": "Israel", "code": "IL" },
    { "es": "Italia", "en": "Italy", "code": "IT" },
    { "es": "Jamaica", "en": "Jamaica", "code": "JM" },
    { "es": "Japón", "en": "Japan", "code": "JP" },
    { "es": "Jersey", "en": "Jersey", "code": "JE" },
    { "es": "Jordania", "en": "Jordan", "code": "JO" },
    { "es": "Kazajistán", "en": "Kazakhstan", "code": "KZ" },
    { "es": "Kenia", "en": "Kenya", "code": "KE" },
    { "es": "Kiribati", "en": "Kiribati", "code": "KI" },
    { "es": "Corea del Sur", "en": "Korea, Republic of", "code": "KR" },
    { "es": "Kuwait", "en": "Kuwait", "code": "KW" },
    { "es": "Kirguistán", "en": "Kyrgyzstan", "code": "KG" },
    { "es": "Laos", "en": "Lao People's Democratic Republic", "code": "LA" },
    { "es": "Letonia", "en": "Latvia", "code": "LV" },
    { "es": "Líbano", "en": "Lebanon", "code": "LB" },
    { "es": "Lesoto", "en": "Lesotho", "code": "LS" },
    { "es": "Liberia", "en": "Liberia", "code": "LR" },
    { "es": "Libia", "en": "Libyan Arab Jamahiriya", "code": "LY" },
    { "es": "Liechtenstein", "en": "Liechtenstein", "code": "LI" },
    { "es": "Lituania", "en": "Lithuania", "code": "LT" },
    { "es": "Luxemburgo", "en": "Luxembourg", "code": "LU" },
    { "es": "Macao", "en": "Macao", "code": "MO" },
    { "es": "Macedonia", "en": "Macedonia", "code": "MK" },
    { "es": "Madagascar", "en": "Madagascar", "code": "MG" },
    { "es": "Malaui", "en": "Malawi", "code": "MW" },
    { "es": "Malasia", "en": "Malaysia", "code": "MY" },
    { "es": "Maldivas", "en": "Maldivas", "code": "MV" },
    { "es": "Malí", "en": "Mali", "code": "ML" },
    { "es": "Malta", "en": "Malta", "code": "MT" },
    { "es": "Isla Marshall", "en": "Marshall Islands", "code": "MH" },
    { "es": "Martinica", "en": "Martinique", "code": "MQ" },
    { "es": "Mauritania", "en": "Mauritania", "code": "MR" },
    { "es": "Mauricio", "en": "Mauritius", "code": "MU" },
    { "es": "Mayotte", "en": "Mayotte", "code": "YT" },
    { "es": "Micronesia", "en": "Micronesia, Federated States of", "code": "FM" },
    { "es": "Moldavia", "en": "Moldova, Republic of", "code": "MD" },
    { "es": "Mónaco", "en": "Monaco", "code": "MC" },
    { "es": "Mongolia", "en": "Mongolia", "code": "MN" },
    { "es": "Montenegro", "en": "Montenegro", "code": "ME" },
    { "es": "Montserrat", "en": "Montserrat", "code": "MS" },
    { "es": "Marruecos", "en": "Morocco", "code": "MA" },
    { "es": "Mozambique", "en": "Mozambique", "code": "MZ" },
    { "es": "Birmania", "en": "Myanmar", "code": "MM" },
    { "es": "Namibia", "en": "Namibia", "code": "NA" },
    { "es": "Nauru", "en": "Nauru", "code": "NR" },
    { "es": "Nepal", "en": "Nepal", "code": "NP" },
    { "es": "Países Bajos", "en": "Netherlands", "code": "NL" },
    { "es": "Nueva Caledonia", "en": "New Caledonia", "code": "NC" },
    { "es": "Nueva Zelanda", "en": "New Zealand", "code": "NZ" },
    { "es": "Nicaragua", "en": "Nicaragua", "code": "NI" },
    { "es": "Níger", "en": "Niger", "code": "NE" },
    { "es": "Nigeria", "en": "Nigeria", "code": "NG" },
    { "es": "Noruega", "en": "Norway", "code": "NO" },
    { "es": "Omán", "en": "Oman", "code": "OM" },
    { "es": "Pakistán", "en": "Pakistan", "code": "PK" },
    { "es": "Palaos", "en": "Palau", "code": "PW" },
    { "es": "Panamá", "en": "Panama", "code": "PA" },
    { "es": "Papúa Nueva Guinea", "en": "Papua New Guinea", "code": "PG" },
    { "es": "Paraguay", "en": "Paraguay", "code": "PY" },
    { "es": "Perú", "en": "Peru", "code": "PE" },
    { "es": "Filipinas", "en": "Philippines", "code": "PH" },
    { "es": "Polonia", "en": "Poland", "code": "PL" },
    { "es": "Portugal", "en": "Portugal", "code": "PT" },
    { "es": "Puerto Rico", "en": "Puerto Rico", "code": "PR" },
    { "es": "Catar", "en": "Qatar", "code": "QA" },
    { "es": "Rumania", "en": "Romania", "code": "RO" },
    { "es": "Rusia", "en": "Russian Federation", "code": "RU" },
    { "es": "Ruanda", "en": "Rwanda", "code": "RW" },
    { "es": "Samoa", "en": "Samoa", "code": "WS" },
    { "es": "San Marino", "en": "San Marino", "code": "SM" },
    { "es": "Arabia Saudita", "en": "Saudi Arabia", "code": "SA" },
    { "es": "Senegal", "en": "Senegal", "code": "SN" },
    { "es": "Serbia", "en": "Serbia", "code": "RS" },
    { "es": "Singapur", "en": "Singapore", "code": "SG" },
    { "es": "Eslovaquia", "en": "Slovakia", "code": "SK" },
    { "es": "Eslovenia", "en": "Slovenia", "code": "SI" },
    { "es": "Somalia", "en": "Somalia", "code": "SO" },
    { "es": "Sudáfrica", "en": "South Africa", "code": "ZA" },
    { "es": "Sri Lanka", "en": "Sri Lanka", "code": "LK" },
    { "es": "Sudán", "en": "Sudan", "code": "SD" },
    { "es": "Suriname", "en": "Suriname", "code": "SR" },
    { "es": "Suecia", "en": "Sweden", "code": "SE" },
    { "es": "Suiza", "en": "Switzerland", "code": "CH" },
    { "es": "Siria", "en": "Syrian Arab Republic", "code": "SY" },
    { "es": "Taiwán", "en": "Taiwan", "code": "TW" },
    { "es": "Tailandia", "en": "Thailand", "code": "TH" },
    { "es": "Togo", "en": "Togo", "code": "TG" },
    { "es": "Tonga", "en": "Tonga", "code": "TO" },
    { "es": "Trinidad y Tobago", "en": "Trinidad and Tobago", "code": "TT" },
    { "es": "Túnez", "en": "Tunisia", "code": "TN" },
    { "es": "Turquía", "en": "Turkey", "code": "TR" },
    { "es": "Ucrania", "en": "Ukraine", "code": "UA" },
    { "es": "Emiratos Árabes Unidos", "en": "United Arab Emirates", "code": "AE" },
    { "es": "Reino Unido", "en": "United Kingdom", "code": "GB" },
    { "es": "Uruguay", "en": "Uruguay", "code": "UY" },
    { "es": "Uzbekistán", "en": "Uzbekistan", "code": "UZ" },
    { "es": "Venezuela", "en": "Venezuela", "code": "VE" },
    { "es": "Vietnam", "en": "Viet Nam", "code": "VN" },
    { "es": "Yemen", "en": "Yemen", "code": "YE" },
    { "es": "Zambia", "en": "Zambia", "code": "ZM" },
    { "es": "Zimbabue", "en": "Zimbabwe", "code": "ZW" }
];
